language: node_js
sudo: require
node_js:
- 8
os: linux
cahce:
  yarn: true
branches:
  only:
  - master
install:
- |
    yarn
script:
- |
    yarn lint && yarn test
after_success:
- |
    yarn coverall
