export {default as accAdd} from './core/accAdd'
export {default as accMul} from './core/accMul'
export {default as accDiv} from './core/accDiv'
export { default as accSub } from './core/accSub'
export {default as addChineseUnit} from './core/addChineseUnit'
export {default as addClass} from './core/addClass'
export { default as anagrams} from './core/anagrams'
export { default as bytesToSize} from './core/bytesToSize'
export { default as capitalizeEveryWord} from './core/capitalizeEveryWord'
export { default as changeMoneyToChinese} from './core/changeMoneyToChinese'
export { default as combineURLs} from './core/combineURLs'
export { default as compareVersion } from './core/compareVersion'
export { default as dataURLToBlob} from './core/dataURLToBlob'
export { default as deepClone } from './core/deepClone'
export { default as hasClass} from './core/hasClass'
